#!/usr/bin/env bash
ROOT_DIR=`git rev-parse --show-toplevel 2>/dev/null`
echo "post merge"
# reinstall if needed
./${ROOT_DIR}/scm/operations/install_git_hooks.sh
# delete pyc files
find ${ROOT_DIR} -name '*.pyc' -delete